version: '1'
name: pagila-container
services:
  app:
    image: crud-docker:latest
    ports:
      - 8080:8080
    build:
      context: .
    container_name: pagila
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pagila
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=evelyn2021

  db:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=evelyn2021
      - POSTGRES_DB=pagila
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5